### PR TITLE
Add command for getting user's current PRs

### LINKED ISSUE #5: Nwe command returning current PRs/comments
Create a new bot command, that would return pr's and comments that are currently stored in the db for particular user.

### PR DESCRIPTION
**Pull request by siemiatj**
This adds a new method for the bot that retrieves Pull Requests currently stored in the DB for this particular user.

Fixes #5

### CODE REVIEW

**Comment by cstyan** [comment]
should this update the last notified time in the database?

**Comment by siemiatj** [comment]
hmm I don't think it should, cause you may still forget about it ;)

**Comment by cstyan** [comment]
Okay sounds good, do you have permission to merge?

**Comment by siemiatj** [comment]
I have now :)

**Pull request merged**
